apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencti-ingress
  namespace: opencti
  annotations:
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "false"
    appgw.ingress.kubernetes.io/request-timeout: "30"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "wildcard-ssl-certificate"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-499"
    appgw.ingress.kubernetes.io/health-probe-path: "/"
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: $(OPENCTI_HOSTNAME)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opencti
                port:
                  number: 8080
